#undef TAPPING_TERM
#define TAPPING_TERM 145

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 3

#define SERIAL_NUMBER "OorKq/Ja0NnO"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 5

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

